In [12]:
import pandas as pd
import re

In [13]:
%pip install spacy

Requirement already satisfied: spacy in d:\anaconda3\lib\site-packages (3.8.16)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in d:\anaconda3\lib\site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in d:\anaconda3\lib\site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in d:\anaconda3\lib\site-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in d:\anaconda3\lib\site-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in d:\anaconda3\lib\site-packages (from spacy) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in d:\anaconda3\lib\site-packages (from spacy) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in d:\anaconda3\lib\site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in d:\anaconda3\lib\site-packages (from spacy) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in d:\anaconda3\lib\site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in d:\anaconda3\lib\site-packages (from spacy) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in d:\anaconda3\lib\site-packages (from spacy) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in d:\anaconda3\lib\site-packages (from spacy) (0.20.0)
Requirement already satisfied: click<9.0.0,>=8.2.1 in d:\anaconda3\lib\site-packages (from spacy) (8.2.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in d:\anaconda3\lib\site-packages (from spacy) (4.67.1)
Requirement already satisfied: numpy>=1.19.0 in d:\anaconda3\lib\site-packages (from spacy) (2.3.5)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in d:\anaconda3\lib\site-packages (from spacy) (2.32.5)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in d:\anaconda3\lib\site-packages (from spacy) (2.12.4)
Requirement already satisfied: jinja2 in d:\anaconda3\lib\site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in d:\anaconda3\lib\site-packages (from spacy) (80.9.0)
Requirement already satisfied: packaging>=20.0 in d:\anaconda3\lib\site-packages (from spacy) (25.0)
Requirement already satisfied: colorama in d:\anaconda3\lib\site-packages (from click<9.0.0,>=8.2.1->spacy) (0.4.6)
Requirement already satisfied: annotated-types>=0.6.0 in d:\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in d:\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in d:\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in d:\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in d:\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in d:\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.1.4)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in d:\anaconda3\lib\site-packages (from thinc<8.4.0,>=8.3.12->spacy) (1.3.3)
Requirement already satisfied: shellingham>=1.3.0 in d:\anaconda3\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in d:\anaconda3\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (14.2.0)
Requirement already satisfied: cloudpathlib>=0.7.0 in d:\anaconda3\lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.25.0)
Requirement already satisfied: smart-open>=5.2.1 in d:\anaconda3\lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (8.0.1)
Requirement already satisfied: httpx>=0.24.0 in d:\anaconda3\lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.28.1)
Requirement already satisfied: anyio in d:\anaconda3\lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (4.10.0)
Requirement already satisfied: httpcore==1.* in d:\anaconda3\lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.9)
Requirement already satisfied: h11>=0.16 in d:\anaconda3\lib\site-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in d:\anaconda3\lib\site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in d:\anaconda3\lib\site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in d:\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
Requirement already satisfied: wrapt in d:\anaconda3\lib\site-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy) (1.17.0)
Requirement already satisfied: sniffio>=1.1 in d:\anaconda3\lib\site-packages (from anyio->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in d:\anaconda3\lib\site-packages (from jinja2->spacy) (3.0.2)
Note: you may need to restart the kernel to use updated packages.

In [14]:
import spacy
from spacy.matcher import PhraseMatcher

In [15]:
df = pd.read_csv("clean_jobs.csv")

df.head()

,job_id,job_title,company,location,job_description,experience,education,salary,job_type,clean_description,original_length,clean_length
0,JOB07402,Frontend Developer,DataBridge Analytics,"Gurgaon, India",We are looking for a Frontend Developer to joi...,1-3 years,B.E.,9-14 LPA,Full-time,we are looking for a frontend developer to joi...,362,351
1,JOB05835,Software Engineer,Vertex Digital,"Mumbai, India",We are looking for a Software Engineer to join...,3-5 years,Bachelor's Degree,12-16 LPA,Internship,we are looking for a software engineer to join...,342,333
2,JOB02123,Machine Learning Engineer,CloudSphere,"Mumbai, India",We are looking for a Machine Learning Engineer...,1-3 years,B.E.,8-11 LPA,Full-time,we are looking for a machine learning engineer...,364,354
3,JOB08789,Cloud Engineer,Apex Solutions,"Mumbai, India",We are looking for a Cloud Engineer to join ou...,3-5 years,Master's Degree,11-16 LPA,Full-time,we are looking for a cloud engineer to join ou...,361,350
4,JOB00305,Frontend Developer,Quantix Technologies,"Noida, India",We are looking for a Frontend Developer to joi...,3-5 years,B.Tech,10-12 LPA,Full-time,we are looking for a frontend developer to joi...,366,355

In [16]:
patterns = {
    "Python": r"\bpython(?:\s*3)?(?:\s+programming)?\b",
    "SQL": r"\bsql\b",
    "Java": r"\bjava\b",
    "C++": r"\bc\+\+\b",
    "JavaScript": r"\bjavascript\b",
    "Power BI": r"\bpower\s*bi\b",
    "AWS": r"\baws\b",
    "Azure": r"\bazure\b",
    "Docker": r"\bdocker\b",
    "Kubernetes": r"\bkubernetes\b"
}

In [17]:
def extract_skills_regex(text):
    found_skills = []

    text = str(text).lower()

    for skill, pattern in patterns.items():
        if re.search(pattern, text):
            found_skills.append(skill)

    return found_skills

In [18]:
df["regex_skills"] = df["clean_description"].apply(
    extract_skills_regex
)

In [19]:
test_texts = [
    "Python developer",
    "Python 3 developer",
    "Python3 programming",
    "Strong Python programming experience"
]

for text in test_texts:
    result = extract_skills_regex(text)
    print(text, "->", result)

Python developer -> ['Python']
Python 3 developer -> ['Python']
Python3 programming -> ['Python']
Strong Python programming experience -> ['Python']

In [20]:
patterns.update({
    "Machine Learning": r"\bmachine\s+learning\b",
    "Deep Learning": r"\bdeep\s+learning\b",
    "Natural Language Processing": r"\bnatural\s+language\s+processing\b",
    "Data Science": r"\bdata\s+science\b"
})

In [21]:
df["regex_skills"] = df["clean_description"].apply(
    extract_skills_regex
)

df[["job_title", "regex_skills"]].head(10)

                   job_title                             regex_skills
0         Frontend Developer                             [JavaScript]
1          Software Engineer                            [Python, SQL]
2  Machine Learning Engineer  [Python, AWS, Docker, Machine Learning]
3             Cloud Engineer         [AWS, Azure, Docker, Kubernetes]
4         Frontend Developer                             [JavaScript]
5               Data Analyst                  [Python, SQL, Power BI]
6  Machine Learning Engineer          [Python, SQL, Machine Learning]
7            DevOps Engineer                        [AWS, Kubernetes]
8                QA Engineer                            [Python, SQL]
9           Business Analyst                          [SQL, Power BI]

In [22]:
nlp = spacy.blank("en")

In [23]:
matcher = PhraseMatcher(nlp.vocab, attr="LOWER")

In [24]:
skill_phrases = [
    "machine learning",
    "deep learning",
    "natural language processing",
    "power bi",
    "data science",
    "computer vision",
    "cloud computing"
]

In [25]:
phrase_patterns = [
    nlp.make_doc(skill)
    for skill in skill_phrases
]

In [26]:
matcher.add("SKILLS", phrase_patterns)

In [27]:
def extract_phrases(text):
    doc = nlp(str(text))

    matches = matcher(doc)

    found = []

    for match_id, start, end in matches:
        phrase = doc[start:end].text
        found.append(phrase)

    return found

In [28]:
text = df["clean_description"].iloc[0]

print(extract_phrases(text))

[]

In [29]:
df["phrase_skills"] = df["clean_description"].apply(
    extract_phrases
)