In [1]:
!pip install spacy

Requirement already satisfied: spacy in d:\anaconda3\lib\site-packages (3.8.16)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in d:\anaconda3\lib\site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in d:\anaconda3\lib\site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in d:\anaconda3\lib\site-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in d:\anaconda3\lib\site-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in d:\anaconda3\lib\site-packages (from spacy) (3.0.13)
Requirement already satisfied: thinc<8.4.0,>=8.3.12 in d:\anaconda3\lib\site-packages (from spacy) (8.3.13)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in d:\anaconda3\lib\site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.5.3 in d:\anaconda3\lib\site-packages (from spacy) (2.5.3)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in d:\anaconda3\lib\site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<2.0.0,>=1.0.0 in d:\anaconda3\lib\site-packages (from spacy) (1.0.0)
Requirement already satisfied: confection<2.0.0,>=1.3.2 in d:\anaconda3\lib\site-packages (from spacy) (1.3.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in d:\anaconda3\lib\site-packages (from spacy) (0.20.0)
Requirement already satisfied: click<9.0.0,>=8.2.1 in d:\anaconda3\lib\site-packages (from spacy) (8.5.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in d:\anaconda3\lib\site-packages (from spacy) (4.67.1)
Requirement already satisfied: numpy>=1.19.0 in d:\anaconda3\lib\site-packages (from spacy) (2.3.5)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in d:\anaconda3\lib\site-packages (from spacy) (2.32.5)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in d:\anaconda3\lib\site-packages (from spacy) (2.12.4)
Requirement already satisfied: jinja2 in d:\anaconda3\lib\site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in d:\anaconda3\lib\site-packages (from spacy) (80.9.0)
Requirement already satisfied: packaging>=20.0 in d:\anaconda3\lib\site-packages (from spacy) (25.0)
Requirement already satisfied: annotated-types>=0.6.0 in d:\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.6.0)
Requirement already satisfied: pydantic-core==2.41.5 in d:\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in d:\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in d:\anaconda3\lib\site-packages (from pydantic<3.0.0,>=2.0.0->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in d:\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in d:\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.1.4)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in d:\anaconda3\lib\site-packages (from thinc<8.4.0,>=8.3.12->spacy) (1.3.3)
Requirement already satisfied: colorama in d:\anaconda3\lib\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Requirement already satisfied: shellingham>=1.3.0 in d:\anaconda3\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=10.11.0 in d:\anaconda3\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (14.2.0)
Requirement already satisfied: cloudpathlib>=0.7.0 in d:\anaconda3\lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.25.0)
Requirement already satisfied: smart-open>=5.2.1 in d:\anaconda3\lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (8.0.1)
Requirement already satisfied: httpx>=0.24.0 in d:\anaconda3\lib\site-packages (from weasel<2.0.0,>=1.0.0->spacy) (0.28.1)
Requirement already satisfied: anyio in d:\anaconda3\lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (4.10.0)
Requirement already satisfied: httpcore==1.* in d:\anaconda3\lib\site-packages (from httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.0.9)
Requirement already satisfied: h11>=0.16 in d:\anaconda3\lib\site-packages (from httpcore==1.*->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (0.16.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in d:\anaconda3\lib\site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in d:\anaconda3\lib\site-packages (from rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in d:\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
Requirement already satisfied: wrapt in d:\anaconda3\lib\site-packages (from smart-open>=5.2.1->weasel<2.0.0,>=1.0.0->spacy) (1.17.0)
Requirement already satisfied: sniffio>=1.1 in d:\anaconda3\lib\site-packages (from anyio->httpx>=0.24.0->weasel<2.0.0,>=1.0.0->spacy) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in d:\anaconda3\lib\site-packages (from jinja2->spacy) (3.0.2)

In [2]:
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
     ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
      --------------------------------------- 0.3/12.8 MB ? eta -:--:--
     - -------------------------------------- 0.5/12.8 MB 1.8 MB/s eta 0:00:07
     -- ------------------------------------- 0.8/12.8 MB 1.4 MB/s eta 0:00:09
     ---- ----------------------------------- 1.3/12.8 MB 1.6 MB/s eta 0:00:07
     ----- ---------------------------------- 1.8/12.8 MB 1.8 MB/s eta 0:00:07
     ------ --------------------------------- 2.1/12.8 MB 1.9 MB/s eta 0:00:06
     -------- ------------------------------- 2.6/12.8 MB 2.0 MB/s eta 0:00:06
     ---------- ----------------------------- 3.4/12.8 MB 2.1 MB/s eta 0:00:05
     ------------ --------------------------- 3.9/12.8 MB 2.2 MB/s eta 0:00:04
     ------------- -------------------------- 4.5/12.8 MB 2.3 MB/s eta 0:00:04
     --------------- ------------------------ 5.0/12.8 MB 2.3 MB/s eta 0:00:04
     ----------------- ---------------------- 5.5/12.8 MB 2.3 MB/s eta 0:00:04
     ------------------ --------------------- 6.0/12.8 MB 2.3 MB/s eta 0:00:03
     -------------------- ------------------- 6.6/12.8 MB 2.4 MB/s eta 0:00:03
     ---------------------- ----------------- 7.3/12.8 MB 2.4 MB/s eta 0:00:03
     ------------------------ --------------- 7.9/12.8 MB 2.4 MB/s eta 0:00:03
     -------------------------- ------------- 8.4/12.8 MB 2.5 MB/s eta 0:00:02
     --------------------------- ------------ 8.9/12.8 MB 2.5 MB/s eta 0:00:02
     ----------------------------- ---------- 9.4/12.8 MB 2.5 MB/s eta 0:00:02
     ------------------------------ --------- 9.7/12.8 MB 2.5 MB/s eta 0:00:02
     ------------------------------- -------- 10.2/12.8 MB 2.4 MB/s eta 0:00:02
     -------------------------------- ------- 10.5/12.8 MB 2.4 MB/s eta 0:00:01
     --------------------------------- ------ 10.7/12.8 MB 2.3 MB/s eta 0:00:01
     ----------------------------------- ---- 11.3/12.8 MB 2.3 MB/s eta 0:00:01
     ------------------------------------ --- 11.5/12.8 MB 2.3 MB/s eta 0:00:01
     ------------------------------------- -- 12.1/12.8 MB 2.3 MB/s eta 0:00:01
     -------------------------------------- - 12.3/12.8 MB 2.2 MB/s eta 0:00:01
     ---------------------------------------  12.6/12.8 MB 2.2 MB/s eta 0:00:01
     ---------------------------------------- 12.8/12.8 MB 2.2 MB/s  0:00:06
Installing collected packages: en-core-web-sm
Successfully installed en-core-web-sm-3.8.0
[+] Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

In [3]:
import pandas as pd
import spacy

In [4]:
df = pd.read_csv("clean_jobs.csv")

print("Dataset Shape:", df.shape)
df.head()

Dataset Shape: (10100, 12)

,job_id,job_title,company,location,job_description,experience,education,salary,job_type,clean_description,original_length,clean_length
0,JOB07402,Frontend Developer,DataBridge Analytics,"Gurgaon, India",We are looking for a Frontend Developer to joi...,1-3 years,B.E.,9-14 LPA,Full-time,we are looking for a frontend developer to joi...,362,351
1,JOB05835,Software Engineer,Vertex Digital,"Mumbai, India",We are looking for a Software Engineer to join...,3-5 years,Bachelor's Degree,12-16 LPA,Internship,we are looking for a software engineer to join...,342,333
2,JOB02123,Machine Learning Engineer,CloudSphere,"Mumbai, India",We are looking for a Machine Learning Engineer...,1-3 years,B.E.,8-11 LPA,Full-time,we are looking for a machine learning engineer...,364,354
3,JOB08789,Cloud Engineer,Apex Solutions,"Mumbai, India",We are looking for a Cloud Engineer to join ou...,3-5 years,Master's Degree,11-16 LPA,Full-time,we are looking for a cloud engineer to join ou...,361,350
4,JOB00305,Frontend Developer,Quantix Technologies,"Noida, India",We are looking for a Frontend Developer to joi...,3-5 years,B.Tech,10-12 LPA,Full-time,we are looking for a frontend developer to joi...,366,355

In [5]:
nlp = spacy.load("en_core_web_sm")

In [6]:
text = df["clean_description"].iloc[0]

doc = nlp(text)

In [7]:
for entity in doc.ents:
    print(entity.text, "->", entity.label_)

git html typescript -> PERSON

In [8]:
custom_entities = {

    "Python": "SKILL",
    "SQL": "SKILL",
    "Java": "SKILL",

    "Power BI": "TOOL",
    "Tableau": "TOOL",
    "Excel": "TOOL",

    "TensorFlow": "TECHNOLOGY",
    "PyTorch": "TECHNOLOGY",
    "Docker": "TECHNOLOGY",

    "PostgreSQL": "DATABASE",
    "MySQL": "DATABASE",
    "MongoDB": "DATABASE",

    "AWS": "CLOUD_PLATFORM",
    "Azure": "CLOUD_PLATFORM",
    "GCP": "CLOUD_PLATFORM"
}

In [9]:
def extract_custom_entities(text):

    found_entities = []

    text = str(text).lower()

    for entity, label in custom_entities.items():

        if entity.lower() in text:

            found_entities.append(
                (entity, label)
            )

    return found_entities

In [10]:
df["custom_entities"] = df[
    "clean_description"
].apply(extract_custom_entities)

In [12]:
df[[
    "job_title",
    "custom_entities"
]].head(10)

,job_title,custom_entities
0,Frontend Developer,"[(Java, SKILL)]"
1,Software Engineer,"[(Python, SKILL), (SQL, SKILL)]"
2,Machine Learning Engineer,"[(Python, SKILL), (TensorFlow, TECHNOLOGY), (P..."
3,Cloud Engineer,"[(Docker, TECHNOLOGY), (AWS, CLOUD_PLATFORM), ..."
4,Frontend Developer,"[(Java, SKILL)]"
5,Data Analyst,"[(Python, SKILL), (SQL, SKILL), (Power BI, TOO..."
6,Machine Learning Engineer,"[(Python, SKILL), (SQL, SKILL), (TensorFlow, T..."
7,DevOps Engineer,"[(AWS, CLOUD_PLATFORM)]"
8,QA Engineer,"[(Python, SKILL), (SQL, SKILL)]"
9,Business Analyst,"[(SQL, SKILL), (Power BI, TOOL), (Tableau, TOO..."

In [15]:
for index, row in df.head(10).iterrows():

    print("Job:", row["job_title"])

    for entity, label in row["custom_entities"]:
        print("  ", entity, "->", label)

    print()

Job: Frontend Developer
   Java -> SKILL

Job: Software Engineer
   Python -> SKILL
   SQL -> SKILL

Job: Machine Learning Engineer
   Python -> SKILL
   TensorFlow -> TECHNOLOGY
   PyTorch -> TECHNOLOGY
   Docker -> TECHNOLOGY
   AWS -> CLOUD_PLATFORM

Job: Cloud Engineer
   Docker -> TECHNOLOGY
   AWS -> CLOUD_PLATFORM
   Azure -> CLOUD_PLATFORM

Job: Frontend Developer
   Java -> SKILL

Job: Data Analyst
   Python -> SKILL
   SQL -> SKILL
   Power BI -> TOOL
   Tableau -> TOOL
   Excel -> TOOL

Job: Machine Learning Engineer
   Python -> SKILL
   SQL -> SKILL
   TensorFlow -> TECHNOLOGY
   PyTorch -> TECHNOLOGY

Job: DevOps Engineer
   AWS -> CLOUD_PLATFORM

Job: QA Engineer
   Python -> SKILL
   SQL -> SKILL

Job: Business Analyst
   SQL -> SKILL
   Power BI -> TOOL
   Tableau -> TOOL
   Excel -> TOOL

In [16]:
from collections import Counter

category_counts = Counter()

for entity_list in df["custom_entities"]:

    for entity, label in entity_list:
        category_counts[label] += 1

print(category_counts)

Counter({'SKILL': 13466, 'TECHNOLOGY': 4999, 'TOOL': 4830, 'CLOUD_PLATFORM': 3587, 'DATABASE': 730})

In [17]:
df.to_csv(
    "custom_ner_results.csv",
    index=False
)

print("Results saved successfully!")

Results saved successfully!