In [2]:
pip install nltk

Requirement already satisfied: nltk in d:\anaconda3\lib\site-packages (3.9.2)
Requirement already satisfied: click in d:\anaconda3\lib\site-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in d:\anaconda3\lib\site-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in d:\anaconda3\lib\site-packages (from nltk) (2025.9.1)
Requirement already satisfied: tqdm in d:\anaconda3\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in d:\anaconda3\lib\site-packages (from click->nltk) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
import nltk

from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer, PorterStemmer

In [4]:
nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")
nltk.download("wordnet")
nltk.download("omw-1.4")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\ASUS\AppData\Roaming\nltk_data...

True

In [10]:
df = pd.read_csv("clean_jobs.csv")

print("Rows:", len(df))
print("Columns:", len(df.columns))

Rows: 10100
Columns: 12

In [11]:
df.head()

,job_id,job_title,company,location,job_description,experience,education,salary,job_type,clean_description,original_length,clean_length
0,JOB07402,Frontend Developer,DataBridge Analytics,"Gurgaon, India",We are looking for a Frontend Developer to joi...,1-3 years,B.E.,9-14 LPA,Full-time,we are looking for a frontend developer to joi...,362,351
1,JOB05835,Software Engineer,Vertex Digital,"Mumbai, India",We are looking for a Software Engineer to join...,3-5 years,Bachelor's Degree,12-16 LPA,Internship,we are looking for a software engineer to join...,342,333
2,JOB02123,Machine Learning Engineer,CloudSphere,"Mumbai, India",We are looking for a Machine Learning Engineer...,1-3 years,B.E.,8-11 LPA,Full-time,we are looking for a machine learning engineer...,364,354
3,JOB08789,Cloud Engineer,Apex Solutions,"Mumbai, India",We are looking for a Cloud Engineer to join ou...,3-5 years,Master's Degree,11-16 LPA,Full-time,we are looking for a cloud engineer to join ou...,361,350
4,JOB00305,Frontend Developer,Quantix Technologies,"Noida, India",We are looking for a Frontend Developer to joi...,3-5 years,B.Tech,10-12 LPA,Full-time,we are looking for a frontend developer to joi...,366,355

In [12]:
text = df["clean_description"].iloc[0]

print(text)

we are looking for a frontend developer to join our team the candidate should have experience with git html typescript react css and javascript the role involves developing solutions analyzing requirements collaborating with cross functional teams and maintaining high quality deliverables strong problem solving and communication skills are preferred

In [13]:
text = text.lower()

print(text)

we are looking for a frontend developer to join our team the candidate should have experience with git html typescript react css and javascript the role involves developing solutions analyzing requirements collaborating with cross functional teams and maintaining high quality deliverables strong problem solving and communication skills are preferred

In [14]:
tokens = word_tokenize(text)

print(tokens)

['we', 'are', 'looking', 'for', 'a', 'frontend', 'developer', 'to', 'join', 'our', 'team', 'the', 'candidate', 'should', 'have', 'experience', 'with', 'git', 'html', 'typescript', 'react', 'css', 'and', 'javascript', 'the', 'role', 'involves', 'developing', 'solutions', 'analyzing', 'requirements', 'collaborating', 'with', 'cross', 'functional', 'teams', 'and', 'maintaining', 'high', 'quality', 'deliverables', 'strong', 'problem', 'solving', 'and', 'communication', 'skills', 'are', 'preferred']

In [15]:
stop_words = set(stopwords.words("english"))

filtered_words = []

for word in tokens:
    if word not in stop_words:
        filtered_words.append(word)

print(filtered_words)

['looking', 'frontend', 'developer', 'join', 'team', 'candidate', 'experience', 'git', 'html', 'typescript', 'react', 'css', 'javascript', 'role', 'involves', 'developing', 'solutions', 'analyzing', 'requirements', 'collaborating', 'cross', 'functional', 'teams', 'maintaining', 'high', 'quality', 'deliverables', 'strong', 'problem', 'solving', 'communication', 'skills', 'preferred']

In [16]:
lemmatizer = WordNetLemmatizer()

lemmatized_words = []

for word in filtered_words:
    lemmatized_words.append(
        lemmatizer.lemmatize(word)
    )

print(lemmatized_words)

['looking', 'frontend', 'developer', 'join', 'team', 'candidate', 'experience', 'git', 'html', 'typescript', 'react', 'cs', 'javascript', 'role', 'involves', 'developing', 'solution', 'analyzing', 'requirement', 'collaborating', 'cross', 'functional', 'team', 'maintaining', 'high', 'quality', 'deliverable', 'strong', 'problem', 'solving', 'communication', 'skill', 'preferred']

In [17]:
stemmer = PorterStemmer()

stemmed_words = []

for word in filtered_words:
    stemmed_words.append(
        stemmer.stem(word)
    )

print(stemmed_words)

['look', 'frontend', 'develop', 'join', 'team', 'candid', 'experi', 'git', 'html', 'typescript', 'react', 'css', 'javascript', 'role', 'involv', 'develop', 'solut', 'analyz', 'requir', 'collabor', 'cross', 'function', 'team', 'maintain', 'high', 'qualiti', 'deliver', 'strong', 'problem', 'solv', 'commun', 'skill', 'prefer']

In [18]:
words = [
    "running",
    "studies",
    "playing",
    "developers"
]

for word in words:

    stem = stemmer.stem(word)
    lemma = lemmatizer.lemmatize(word)

    print("Word:", word)
    print("Stem:", stem)
    print("Lemma:", lemma)
    print()

Word: running
Stem: run
Lemma: running

Word: studies
Stem: studi
Lemma: study

Word: playing
Stem: play
Lemma: playing

Word: developers
Stem: develop
Lemma: developer

In [19]:
sentences = sent_tokenize(text)

for sentence in sentences:
    print(sentence)

we are looking for a frontend developer to join our team the candidate should have experience with git html typescript react css and javascript the role involves developing solutions analyzing requirements collaborating with cross functional teams and maintaining high quality deliverables strong problem solving and communication skills are preferred

In [21]:
def preprocess_text(text):

    # Lowercase
    text = text.lower()

    # Tokenization
    tokens = word_tokenize(text)

    # Remove stopwords
    tokens = [
        word for word in tokens
        if word not in stop_words
    ]

    # Lemmatization
    tokens = [
        lemmatizer.lemmatize(word)
        for word in tokens
    ]

    return tokens

In [22]:
result = preprocess_text(
    df["clean_description"].iloc[0]
)

print(result)

['looking', 'frontend', 'developer', 'join', 'team', 'candidate', 'experience', 'git', 'html', 'typescript', 'react', 'cs', 'javascript', 'role', 'involves', 'developing', 'solution', 'analyzing', 'requirement', 'collaborating', 'cross', 'functional', 'team', 'maintaining', 'high', 'quality', 'deliverable', 'strong', 'problem', 'solving', 'communication', 'skill', 'preferred']

In [23]:
df["processed_text"] = df["clean_description"].apply(
    preprocess_text
)

In [24]:
df[[
    "job_title",
    "clean_description",
    "processed_text"
]].head()

,job_title,clean_description,processed_text
0,Frontend Developer,we are looking for a frontend developer to joi...,"[looking, frontend, developer, join, team, can..."
1,Software Engineer,we are looking for a software engineer to join...,"[looking, software, engineer, join, team, cand..."
2,Machine Learning Engineer,we are looking for a machine learning engineer...,"[looking, machine, learning, engineer, join, t..."
3,Cloud Engineer,we are looking for a cloud engineer to join ou...,"[looking, cloud, engineer, join, team, candida..."
4,Frontend Developer,we are looking for a frontend developer to joi...,"[looking, frontend, developer, join, team, can..."

In [25]:
df.to_csv(
    "preprocessed_jobs.csv",
    index=False
)

print("Preprocessing completed successfully!")

Preprocessing completed successfully!